// src/lib/imagevariants.ts

/**
 * Physical variants generated by your upload pipeline.
 *
 * Example files for a base path "sites/123/gallery1.jpg":
 *   sites/123/gallery1_thumb.jpg
 *   sites/123/gallery1_sm.jpg
 *   sites/123/gallery1_md.jpg
 *   sites/123/gallery1_lg.jpg
 *   sites/123/gallery1_hero.jpg
 */
export type ImageVariantKey = "thumb" | "sm" | "md" | "lg" | "hero";

/**
 * Supabase storage bucket name for site images.
 * This matches what you already use.
 */
export const SITE_IMAGES_BUCKET = "site-images";

/**
 * Returns the base Supabase URL for public storage reads.
 * Uses NEXT_PUBLIC_SUPABASE_URL so it works on client and server.
 */
export function getSupabasePublicBaseUrl(): string {
  const base = process.env.NEXT_PUBLIC_SUPABASE_URL;

  if (!base) {
    throw new Error(
      "NEXT_PUBLIC_SUPABASE_URL is not set. Check your environment variables."
    );
  }

  // Remove trailing slashes to avoid "//" in final URL
  return base.replace(/\/+$/, "");
}

/**
 * Normalizes a storage path from the database.
 * Currently just removes leading slashes.
 *
 * Example:
 *   "/sites/123/gallery1.jpg" -> "sites/123/gallery1.jpg"
 */
export function normalizeStoragePath(path: string): string {
  return path.replace(/^\/+/, "");
}

/**
 * Builds the storage path for a variant using your suffix convention.
 *
 * Examples:
 *   baseStoragePath = "sites/123/gallery1.jpg", variant = "thumb"
 *   -> "sites/123/gallery1_thumb.jpg"
 *
 *   baseStoragePath = "sites/123/gallery1", variant = "md"
 *   -> "sites/123/gallery1_md"
 */
/** Strip any existing variant suffix from a base name (before extension). */
function stripVariantSuffix(name: string): string {
  return name.replace(/_(?:thumb|sm|md|lg|hero)$/, "");
}

export function makeVariantPath(
  baseStoragePath: string,
  variant: ImageVariantKey
): string {
  const clean = normalizeStoragePath(baseStoragePath);
  const lastDot = clean.lastIndexOf(".");

  // No extension present. Just append suffix.
  if (lastDot === -1) {
    return `${stripVariantSuffix(clean)}_${variant}`;
  }

  const name = stripVariantSuffix(clean.slice(0, lastDot));
  const ext = clean.slice(lastDot);
  return `${name}_${variant}${ext}`;
}

/**
 * Returns the storage path for a variant or the base path if no variant is given.
 *
 * Examples:
 *   getVariantStoragePath("sites/123/gallery1.jpg", "md")
 *   -> "sites/123/gallery1_md.jpg"
 *
 *   getVariantStoragePath("sites/123/gallery1.jpg", null)
 *   -> "sites/123/gallery1.jpg"
 */
export function getVariantStoragePath(
  baseStoragePath: string,
  variant?: ImageVariantKey | null
): string {
  if (!variant) {
    return normalizeStoragePath(baseStoragePath);
  }

  return makeVariantPath(baseStoragePath, variant);
}

/**
 * Builds the public URL for a file in the site-images bucket.
 * This is the base form with no variant suffix applied.
 *
 * Example:
 *   buildPublicUrlFromStoragePath("sites/123/gallery1.jpg")
 *   -> "https://xyz.supabase.co/storage/v1/object/public/site-images/sites/123/gallery1.jpg"
 */
export function buildPublicUrlFromStoragePath(storagePath: string): string {
  const baseUrl = getSupabasePublicBaseUrl();
  const clean = normalizeStoragePath(storagePath);
  return `${baseUrl}/storage/v1/object/public/${SITE_IMAGES_BUCKET}/${clean}`;
}

/**
 * Builds the public URL for a given variant.
 * If no variant is provided, uses the base storage path.
 *
 * Examples:
 *   getVariantPublicUrl("sites/123/gallery1.jpg", "thumb")
 *   -> ".../site-images/sites/123/gallery1_thumb.jpg"
 *
 *   getVariantPublicUrl("sites/123/gallery1.jpg", undefined)
 *   -> ".../site-images/sites/123/gallery1.jpg"
 */
export function getVariantPublicUrl(
  baseStoragePath: string,
  variant?: ImageVariantKey | null
): string {
  const variantPath = getVariantStoragePath(baseStoragePath, variant);
  return buildPublicUrlFromStoragePath(variantPath);
}

const SITE_IMAGES_MARK = "/site-images/";

/**
 * Returns a thumbnail/size URL without using Supabase Image Transformations (avoids billing).
 * For site-images: uses pre-generated variant (thumb/md/etc). For other Supabase URLs: direct public URL.
 */
export function getThumbOrVariantUrlNoTransform(
  input: string | null | undefined,
  variant: ImageVariantKey = "thumb"
): string {
  if (!input?.trim()) return "";
  const base = getSupabasePublicBaseUrl();
  const trimmed = input.trim();
  if (/^https?:\/\//i.test(trimmed)) {
    if (!trimmed.startsWith(base)) return trimmed;
    const idx = trimmed.indexOf(SITE_IMAGES_MARK);
    if (idx !== -1) {
      const path = decodeURIComponent(trimmed.slice(idx + SITE_IMAGES_MARK.length).split("?")[0]);
      return getVariantPublicUrl(path, variant);
    }
    return trimmed.split("?")[0];
  }
  return getVariantPublicUrl(normalizeStoragePath(trimmed), variant);
}
